/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const QueryLazyImport = createFileRoute('/query')()
const AddPatientLazyImport = createFileRoute('/add-patient')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const QueryLazyRoute = QueryLazyImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/query.lazy').then((d) => d.Route))

const AddPatientLazyRoute = AddPatientLazyImport.update({
  id: '/add-patient',
  path: '/add-patient',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/add-patient.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/add-patient': {
      id: '/add-patient'
      path: '/add-patient'
      fullPath: '/add-patient'
      preLoaderRoute: typeof AddPatientLazyImport
      parentRoute: typeof rootRoute
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/add-patient': typeof AddPatientLazyRoute
  '/query': typeof QueryLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/add-patient': typeof AddPatientLazyRoute
  '/query': typeof QueryLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/add-patient': typeof AddPatientLazyRoute
  '/query': typeof QueryLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-patient' | '/query'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-patient' | '/query'
  id: '__root__' | '/' | '/add-patient' | '/query'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AddPatientLazyRoute: typeof AddPatientLazyRoute
  QueryLazyRoute: typeof QueryLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AddPatientLazyRoute: AddPatientLazyRoute,
  QueryLazyRoute: QueryLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add-patient",
        "/query"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/add-patient": {
      "filePath": "add-patient.lazy.tsx"
    },
    "/query": {
      "filePath": "query.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
